# Generated by Django 6.0 on 2025-12-31 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='transport.trip'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'timestamp'], name='attendance_student_75d804_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['trip', '-timestamp'], name='attendance_trip_id_7ebd01_idx'),
        ),
    ]
