# Generated by Django 6.0 on 2026-01-13 04:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pricing_config', models.JSONField(default=dict, help_text='Global pricing for plans/modules')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('feature_flags', models.JSONField(default=dict, help_text='Global feature toggles')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
            ],
            options={
                'verbose_name': 'Global Settings',
                'verbose_name_plural': 'Global Settings',
                'db_table': 'global_settings',
            },
        ),
        migrations.AddField(
            model_name='school',
            name='data_usage',
            field=models.BigIntegerField(default=0, help_text='Data usage in bytes'),
        ),
        migrations.AddField(
            model_name='school',
            name='features_config',
            field=models.JSONField(blank=True, default=dict, help_text='Specific feature toggles for this school'),
        ),
        migrations.AddField(
            model_name='school',
            name='pricing_plan',
            field=models.CharField(default='standard', help_text='Pricing plan tier', max_length=50),
        ),
    ]
