# Generated by Django 6.0 on 2026-01-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_globalsettings_school_data_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='affiliation_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='board',
            field=models.CharField(blank=True, help_text='e.g. CBSE, ICSE, State Board', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='capacity',
            field=models.IntegerField(default=0, help_text='Total student capacity'),
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='facilities',
            field=models.JSONField(blank=True, default=list, help_text='List of available facilities'),
        ),
        migrations.AddField(
            model_name='school',
            name='medium',
            field=models.CharField(blank=True, help_text='e.g. English, Hindi', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='principal_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(choices=[('co-ed', 'Co-Ed'), ('boys', 'Boys'), ('girls', 'Girls')], default='co-ed', max_length=20),
        ),
    ]
