# Generated by Django 6.0 on 2026-01-14 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_affiliation_number_school_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='high_class',
            field=models.CharField(blank=True, help_text='Highest Grade (e.g. Class 12)', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='low_class',
            field=models.CharField(blank=True, help_text='Lowest Grade (e.g. Nursery)', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='udise_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
