# Generated by Django 6.0 on 2026-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_high_class_school_low_class_school_udise_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='streams',
            field=models.JSONField(blank=True, default=list, help_text='Available streams for 11/12'),
        ),
    ]
