# Generated by Django 6.0 on 2026-01-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_streams'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='staff_count',
            field=models.IntegerField(default=0, help_text='Total number of support staff'),
        ),
        migrations.AddField(
            model_name='school',
            name='teacher_count',
            field=models.IntegerField(default=0, help_text='Total number of teachers'),
        ),
    ]
