# Generated by Django 6.0 on 2026-01-14 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_staff_count_school_teacher_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
