# Generated by Django 6.0 on 2026-01-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.feature'),
        ),
    ]
