# Generated by Django 6.0 on 2026-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_transaction_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='pricing_type',
            field=models.CharField(choices=[('flat', 'Flat Rate'), ('tiered', 'Tiered Pricing')], default='flat', max_length=20),
        ),
        migrations.AddField(
            model_name='feature',
            name='tiers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
