# Generated by Django 6.0 on 2025-12-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmembership',
            name='role',
            field=models.CharField(choices=[('root_admin', 'Root Admin'), ('school_admin', 'School Admin'), ('office_staff', 'Office Staff'), ('teacher', 'Teacher'), ('conductor', 'Conductor'), ('driver', 'Driver'), ('parent', 'Parent'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('nurse', 'Nurse'), ('security', 'Security'), ('helper', 'Helper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('root_admin', 'Root Admin'), ('school_admin', 'School Admin'), ('office_staff', 'Office Staff'), ('teacher', 'Teacher'), ('conductor', 'Conductor'), ('driver', 'Driver'), ('parent', 'Parent'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('nurse', 'Nurse'), ('security', 'Security'), ('helper', 'Helper')], default='parent', max_length=20),
        ),
    ]
