# Generated by Django 6.0 on 2026-01-21 16:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_schoolmembership_role_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('father_name', models.CharField(blank=True, max_length=150, null=True, verbose_name="Father's/Spouse Name")),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True)),
                ('nationality', models.CharField(blank=True, default='Indian', max_length=50)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('present_address', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('id_type', models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('pan', 'PAN Card'), ('driving_license', 'Driving License')], max_length=20, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('languages_known', models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=200, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_class', models.CharField(blank=True, choices=[('hmv', 'HMV (Heavy Motor Vehicle)'), ('transport', 'Transport Vehicle'), ('psv', 'PSV/PSC (Passenger Stage Carriage)'), ('lmv', 'LMV (Light Motor Vehicle)')], max_length=20, null=True)),
                ('license_rta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Issuing RTA/State')),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('license_endorsements', models.CharField(blank=True, help_text='PSV Badge, etc.', max_length=200, null=True)),
                ('conductor_license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('conductor_license_authority', models.CharField(blank=True, max_length=100, null=True)),
                ('conductor_license_valid_until', models.DateField(blank=True, null=True)),
                ('willing_to_obtain_license', models.BooleanField(default=False)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience')),
                ('education', models.CharField(blank=True, max_length=200, null=True, verbose_name='Educational Qualification')),
                ('previous_employment', models.TextField(blank=True, help_text='Previous employer details', null=True)),
                ('professional_training', models.CharField(blank=True, help_text='First aid, defensive driving, etc.', max_length=300, null=True)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height (cm)')),
                ('weight_kg', models.PositiveIntegerField(blank=True, null=True, verbose_name='Weight (kg)')),
                ('vision_status', models.CharField(blank=True, choices=[('normal', 'Normal'), ('with_glasses', 'With Glasses'), ('with_contacts', 'With Contact Lenses')], max_length=20, null=True)),
                ('medical_history', models.TextField(blank=True, help_text='Chronic illnesses, prior accidents', null=True)),
                ('fitness_confirmed', models.BooleanField(default=False, verbose_name='Physically fit to work')),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to='medical_certificates/')),
                ('police_verification_obtained', models.BooleanField(default=False)),
                ('police_verification_certificate', models.FileField(blank=True, null=True, upload_to='police_certificates/')),
                ('no_criminal_record', models.BooleanField(default=False)),
                ('available_start_date', models.DateField(blank=True, null=True)),
                ('preferred_working_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('last_drawn_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('willing_fulltime', models.BooleanField(default=True)),
                ('understands_duties', models.BooleanField(default=False)),
                ('declaration_signed', models.BooleanField(default=False)),
                ('declaration_date', models.DateField(blank=True, null=True)),
                ('id_proof_document', models.FileField(blank=True, null=True, upload_to='staff_documents/id/')),
                ('address_proof_document', models.FileField(blank=True, null=True, upload_to='staff_documents/address/')),
                ('education_certificate', models.FileField(blank=True, null=True, upload_to='staff_documents/education/')),
                ('experience_certificate', models.FileField(blank=True, null=True, upload_to='staff_documents/experience/')),
                ('license_document', models.FileField(blank=True, null=True, upload_to='staff_documents/license/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'staff_profiles',
            },
        ),
    ]
