# Generated by Django 6.0 on 2026-01-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='criminal_record_certificate',
            field=models.FileField(blank=True, null=True, upload_to='criminal_certificates/'),
        ),
    ]
