# Generated by Django 6.0 on 2026-01-25 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffprofile_criminal_record_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('education_qualification', models.CharField(blank=True, max_length=100)),
                ('government_id_type', models.CharField(blank=True, choices=[('aadhar', 'Aadhar Card'), ('voter_id', 'Voter ID'), ('passport', 'Passport'), ('pan', 'PAN Card'), ('driving_license', 'Driving License')], max_length=30)),
                ('government_id_number', models.CharField(blank=True, max_length=50)),
                ('is_alumni', models.BooleanField(default=False)),
                ('alumni_year', models.CharField(blank=True, max_length=4)),
                ('alumni_house', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='parent_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
    ]
