/**
 * Trip Summary Screen - Shows completed trip statistics
 */

import React from 'react';
import {
    View,
    Text,
    StyleSheet,
    ScrollView,
    SafeAreaView,
    Share,
} from 'react-native';
import { ConductorScreenProps } from '../../types/navigation';
import { useGetTripAttendanceQuery } from '../../store/api';
import { colors } from '../../constants/colors';
import { theme } from '../../constants/theme';
import Icon from 'react-native-vector-icons/MaterialIcons';
import { Card, LoadingSpinner, Button, Avatar } from '../../components/common';

const TripSummaryScreen: React.FC<ConductorScreenProps<'TripSummary'>> = ({
    route,
    navigation,
}) => {
    const { tripId } = route.params;

    const { data: attendanceData, isLoading } = useGetTripAttendanceQuery(tripId);

    const handleShare = async () => {
        const stats = attendanceData;
        const message = `
Trip Summary - ${new Date().toLocaleDateString()}

Bus: ${stats?.trip?.bus_number || 'N/A'}
Route: ${stats?.trip?.route_name || 'N/A'}
Type: ${stats?.trip?.trip_type === 'morning' ? 'Morning Pickup' : 'Evening Drop'}

Students:
- Total: ${stats?.total_students || 0}
- Boarded: ${stats?.checked_in_count || 0}
- Dropped: ${stats?.checked_out_count || 0}

Generated by ThreeSixty App
    `.trim();

        await Share.share({ message });
    };

    if (isLoading) {
        return <LoadingSpinner fullScreen text="Loading summary..." />;
    }

    const stats = {
        total: attendanceData?.total_students || 0,
        boarded: attendanceData?.checked_in_count || 0,
        dropped: attendanceData?.checked_out_count || 0,
        pending: (attendanceData?.total_students || 0) - (attendanceData?.checked_out_count || 0),
    };

    const completionRate = stats.total > 0
        ? Math.round((stats.dropped / stats.total) * 100)
        : 0;

    const trip = attendanceData?.trip;

    return (
        <SafeAreaView style={styles.container}>
            <ScrollView contentContainerStyle={styles.scrollContent}>
                {/* Success Header */}
                <View style={styles.successHeader}>
                    <Icon name="emoji-events" size={64} color={colors.warning} style={{ marginBottom: theme.spacing.md }} />
                    <Text style={styles.successTitle}>Trip Completed!</Text>
                    <Text style={styles.successSubtitle}>
                        {new Date().toLocaleDateString('en-US', {
                            weekday: 'long',
                            year: 'numeric',
                            month: 'long',
                            day: 'numeric'
                        })}
                    </Text>
                </View>

                {/* Trip Info */}
                <Card style={styles.tripCard}>
                    <View style={styles.tripRow}>
                        <View style={styles.tripInfo}>
                            <Text style={styles.tripLabel}>Bus</Text>
                            <Text style={styles.tripValue}>{trip?.bus_number || 'N/A'}</Text>
                        </View>
                        <View style={styles.tripInfo}>
                            <Text style={styles.tripLabel}>Route</Text>
                            <Text style={styles.tripValue}>{trip?.route_name || 'N/A'}</Text>
                        </View>
                        <View style={styles.tripInfo}>
                            <Text style={styles.tripLabel}>Type</Text>
                            <View style={styles.tripValue}>
                                {trip?.trip_type === 'morning' ? (
                                    <Icon name="wb-sunny" size={24} color={colors.warning} />
                                ) : (
                                    <Icon name="nights-stay" size={24} color={colors.primary} />
                                )}
                            </View>
                        </View>
                    </View>
                </Card>

                {/* Stats Cards */}
                <View style={styles.statsGrid}>
                    <Card style={styles.statCard}>
                        <Text style={styles.statNumber}>{stats.total}</Text>
                        <Text style={styles.statLabel}>Total Students</Text>
                    </Card>
                    <Card style={[styles.statCard, { backgroundColor: colors.successLight || '#E8F5E9' }]}>
                        <Text style={[styles.statNumber, { color: colors.success }]}>{stats.boarded}</Text>
                        <Text style={styles.statLabel}>Boarded</Text>
                    </Card>
                    <Card style={[styles.statCard, { backgroundColor: colors.infoLight || '#E3F2FD' }]}>
                        <Text style={[styles.statNumber, { color: colors.info }]}>{stats.dropped}</Text>
                        <Text style={styles.statLabel}>Dropped</Text>
                    </Card>
                    <Card style={[styles.statCard, { backgroundColor: stats.pending > 0 ? '#FFF3E0' : '#E8F5E9' }]}>
                        <Text style={[styles.statNumber, { color: stats.pending > 0 ? colors.warning : colors.success }]}>
                            {stats.pending}
                        </Text>
                        <Text style={styles.statLabel}>Pending</Text>
                    </Card>
                </View>

                {/* Completion Rate */}
                <Card style={styles.completionCard}>
                    <Text style={styles.completionTitle}>Completion Rate</Text>
                    <View style={styles.progressContainer}>
                        <View style={styles.progressBar}>
                            <View
                                style={[
                                    styles.progressFill,
                                    {
                                        width: `${completionRate}%`,
                                        backgroundColor: completionRate === 100 ? colors.success : colors.primary,
                                    }
                                ]}
                            />
                        </View>
                        <Text style={styles.progressText}>{completionRate}%</Text>
                    </View>
                    {completionRate === 100 ? (
                        <View style={styles.completeBadge}>
                            <Icon name="check-circle" size={16} color={colors.success} style={{ marginRight: 6 }} />
                            <Text style={styles.completeBadgeText}>All students dropped successfully</Text>
                        </View>
                    ) : (
                        <Text style={styles.pendingNote}>
                            {stats.pending} student(s) still need to be dropped off
                        </Text>
                    )}
                </Card>

                {/* Timeline (if available) */}
                {attendanceData?.students && attendanceData.students.length > 0 && (
                    <Card style={styles.timelineCard}>
                        <Text style={styles.timelineTitle}>Attendance Timeline</Text>
                        {attendanceData.students.slice(0, 5).map((item: any, index: number) => (
                            <View key={item.student.id} style={styles.timelineItem}>
                                <Avatar
                                    source={item.student.photo}
                                    name={item.student.full_name}
                                    size="small"
                                />
                                <View style={styles.timelineInfo}>
                                    <Text style={styles.timelineName}>{item.student.full_name}</Text>
                                    <View style={{ flexDirection: 'row', alignItems: 'center', marginTop: 2 }}>
                                        <Icon
                                            name={item.checkout ? 'check-circle' : item.checkin ? 'directions-bus' : 'schedule'}
                                            size={12}
                                            color={colors.textSecondary}
                                            style={{ marginRight: 4 }}
                                        />
                                        <Text style={styles.timelineStatus}>
                                            {item.checkout ? 'Dropped' : item.checkin ? 'On Bus' : 'Pending'}
                                        </Text>
                                    </View>
                                </View>
                                {item.checkout && (
                                    <Text style={styles.timelineTime}>
                                        {new Date(item.checkout.timestamp).toLocaleTimeString([], {
                                            hour: '2-digit',
                                            minute: '2-digit'
                                        })}
                                    </Text>
                                )}
                            </View>
                        ))}
                        {attendanceData.students.length > 5 && (
                            <Text style={styles.moreStudents}>
                                +{attendanceData.students.length - 5} more students
                            </Text>
                        )}
                    </Card>
                )}

                {/* Actions */}
                <View style={styles.actions}>
                    <Button
                        title="Share Summary"
                        icon={<Icon name="share" size={20} color={colors.primary} />}
                        onPress={handleShare}
                        variant="outline"
                        style={styles.actionButton}
                    />
                    <Button
                        title="Back to Home"
                        icon={<Icon name="home" size={20} color={colors.white} />}
                        onPress={() => navigation.navigate('ConductorHome')}
                        style={styles.actionButton}
                    />
                </View>
            </ScrollView>
        </SafeAreaView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
    },
    scrollContent: {
        padding: theme.spacing.md,
        paddingBottom: theme.spacing.xxl,
    },
    successHeader: {
        alignItems: 'center',
        paddingVertical: theme.spacing.xl,
    },
    successIcon: {
        fontSize: 64,
        marginBottom: theme.spacing.md,
    },
    successTitle: {
        fontSize: theme.typography.fontSize.xxxl,
        fontWeight: '700',
        color: colors.textPrimary,
        marginBottom: theme.spacing.xs,
    },
    successSubtitle: {
        fontSize: theme.typography.fontSize.md,
        color: colors.textSecondary,
    },
    tripCard: {
        marginBottom: theme.spacing.lg,
    },
    tripRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    tripInfo: {
        alignItems: 'center',
    },
    tripLabel: {
        fontSize: theme.typography.fontSize.sm,
        color: colors.textSecondary,
        marginBottom: 4,
    },
    tripValue: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: '600',
        color: colors.textPrimary,
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: theme.spacing.md,
        marginBottom: theme.spacing.lg,
    },
    statCard: {
        width: '47%',
        alignItems: 'center',
        padding: theme.spacing.lg,
    },
    statNumber: {
        fontSize: 36,
        fontWeight: '700',
        color: colors.textPrimary,
    },
    statLabel: {
        fontSize: theme.typography.fontSize.sm,
        color: colors.textSecondary,
        marginTop: theme.spacing.xs,
    },
    completionCard: {
        marginBottom: theme.spacing.lg,
        padding: theme.spacing.lg,
    },
    completionTitle: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: '600',
        color: colors.textPrimary,
        marginBottom: theme.spacing.md,
    },
    progressContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: theme.spacing.md,
    },
    progressBar: {
        flex: 1,
        height: 12,
        backgroundColor: colors.border,
        borderRadius: 6,
        overflow: 'hidden',
        marginRight: theme.spacing.md,
    },
    progressFill: {
        height: '100%',
        borderRadius: 6,
    },
    progressText: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: '600',
        color: colors.textPrimary,
        minWidth: 50,
        textAlign: 'right',
    },
    completeBadge: {
        backgroundColor: colors.successLight || '#E8F5E9',
        padding: theme.spacing.sm,
        borderRadius: theme.borderRadius.md,
        alignItems: 'center',
    },
    completeBadgeText: {
        color: colors.success,
        fontWeight: '500',
        fontSize: theme.typography.fontSize.sm,
    },
    pendingNote: {
        fontSize: theme.typography.fontSize.sm,
        color: colors.warning,
        textAlign: 'center',
    },
    timelineCard: {
        marginBottom: theme.spacing.lg,
    },
    timelineTitle: {
        fontSize: theme.typography.fontSize.lg,
        fontWeight: '600',
        color: colors.textPrimary,
        marginBottom: theme.spacing.md,
    },
    timelineItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: theme.spacing.sm,
        borderBottomWidth: 1,
        borderBottomColor: colors.divider,
    },
    timelineInfo: {
        flex: 1,
        marginLeft: theme.spacing.md,
    },
    timelineName: {
        fontSize: theme.typography.fontSize.md,
        fontWeight: '500',
        color: colors.textPrimary,
    },
    timelineStatus: {
        fontSize: theme.typography.fontSize.sm,
        color: colors.textSecondary,
        marginTop: 2,
    },
    timelineTime: {
        fontSize: theme.typography.fontSize.sm,
        color: colors.textHint,
    },
    moreStudents: {
        fontSize: theme.typography.fontSize.sm,
        color: colors.primary,
        textAlign: 'center',
        marginTop: theme.spacing.md,
    },
    actions: {
        gap: theme.spacing.md,
    },
    actionButton: {
        marginBottom: 0,
    },
});

export default TripSummaryScreen;
