# Generated by Django 6.0 on 2025-12-31 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.route'),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.AddField(
            model_name='student',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='transport.stop'),
        ),
        migrations.AddField(
            model_name='parent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='students.student'),
        ),
        migrations.AddField(
            model_name='faceencoding',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'admission_number')},
        ),
        migrations.AlterUniqueTogether(
            name='parent',
            unique_together={('user', 'student')},
        ),
    ]
