# Generated by Django 6.0 on 2026-01-25 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_school_code'),
        ('students', '0003_alter_student_pickup_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='has_legal_restraining_order',
            field=models.BooleanField(default=False, help_text='RED FLAG - Court order'),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_custodial_parent',
            field=models.BooleanField(default=True, help_text='Parent with physical custody'),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_local_guardian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parent',
            name='is_primary_payer',
            field=models.BooleanField(default=False, help_text='Billing responsibility'),
        ),
        migrations.AddField(
            model_name='parent',
            name='lg_address',
            field=models.TextField(blank=True, help_text='Local guardian address'),
        ),
        migrations.AddField(
            model_name='parent',
            name='lg_authorization_level',
            field=models.CharField(blank=True, choices=[('full', 'Full Authorization (Medical + Logistical)'), ('medical_only', 'Medical Decisions Only'), ('logistical_only', 'Logistical Decisions Only'), ('emergency_only', 'Emergency Only')], help_text='Level of authority for local guardian', max_length=50),
        ),
        migrations.AddField(
            model_name='parent',
            name='lg_proximity_km',
            field=models.PositiveIntegerField(blank=True, help_text='Distance from school in km', null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='lg_visiting_rights',
            field=models.CharField(blank=True, choices=[('weekend_exeat', 'Allowed Weekend Exeats'), ('campus_only', 'Campus Visits Only'), ('no_visits', 'No Visiting Rights')], help_text='Visiting/exeat permissions', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='area_classification',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('rural', 'Rural')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='student',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='behavior_contract_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='bpl_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='bpl_status',
            field=models.BooleanField(default=False, help_text='Below Poverty Line'),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_acceptable_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_data_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_emergency_medical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_field_trips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_social_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_third_party_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_website_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='consent_yearbook_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='current_building_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_house_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='current_locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='current_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='current_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('locomotor', 'Locomotor Disability'), ('cognitive', 'Cognitive/Intellectual'), ('multiple', 'Multiple Disabilities'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='ews_certificate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='ews_status',
            field=models.BooleanField(default=False, help_text='Economically Weaker Section'),
        ),
        migrations.AddField(
            model_name='student',
            name='frro_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='has_sibling_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='has_tc',
            field=models.BooleanField(default=True, help_text='Has Transfer Certificate'),
        ),
        migrations.AddField(
            model_name='student',
            name='indemnity_bond_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_aadhar_seeded',
            field=models.BooleanField(default=False, help_text='Bank linked to Aadhaar'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_cwsn',
            field=models.BooleanField(default=False, help_text='Children with Special Needs'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='is_oci',
            field=models.BooleanField(default=False, help_text='Overseas Citizen of India'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_rte_quota',
            field=models.BooleanField(default=False, help_text='Right to Education quota'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_staff_ward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_class_result',
            field=models.CharField(blank=True, choices=[('passed', 'Passed'), ('failed', 'Failed'), ('promoted', 'Promoted on Trial')], max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='last_class_studied',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='oci_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_building_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_house_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_locality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_street',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_board',
            field=models.CharField(blank=True, choices=[('cbse', 'CBSE'), ('icse', 'ICSE/ISC'), ('ib', 'IB'), ('igcse', 'Cambridge IGCSE'), ('state', 'State Board'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_medium',
            field=models.CharField(blank=True, choices=[('english', 'English'), ('hindi', 'Hindi'), ('regional', 'Regional Language')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, choices=[('hindu', 'Hindu'), ('muslim', 'Muslim'), ('christian', 'Christian'), ('sikh', 'Sikh'), ('buddhist', 'Buddhist'), ('jain', 'Jain'), ('parsi', 'Parsi'), ('jewish', 'Jewish'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='same_as_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='scholarship_type',
            field=models.CharField(blank=True, help_text='Merit/Sports/Other', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='sibling_admission_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_subjects',
            field=models.JSONField(blank=True, default=list, help_text='For Class 9-10'),
        ),
        migrations.AddField(
            model_name='student',
            name='social_category',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('sc', 'SC (Scheduled Caste)'), ('st', 'ST (Scheduled Tribe)'), ('obc', 'OBC (Other Backward Class)'), ('ews', 'EWS (Economically Weaker Section)')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(choices=[('day_scholar', 'Day Scholar'), ('boarder', 'Boarder'), ('weekly_boarder', 'Weekly Boarder')], default='day_scholar', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='tc_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='tc_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='third_language',
            field=models.CharField(blank=True, help_text='Sanskrit/French/German etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('school_bus', 'School Bus'), ('private_car', 'Private Car'), ('walk', 'Walk'), ('public_transport', 'Public Transport'), ('bicycle', 'Bicycle')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_opted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='visa_type',
            field=models.CharField(blank=True, help_text='S-Visa/X-Visa/Diplomatic', max_length=30),
        ),
        migrations.AlterField(
            model_name='parent',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary contact'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relation',
            field=models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('step_father', 'Step-Father'), ('step_mother', 'Step-Mother'), ('guardian', 'Legal Guardian'), ('grandparent', 'Grandparent'), ('local_guardian', 'Local Guardian'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('transgender', 'Transgender')], max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='pickup_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(help_text='School UUID - ensures data isolation', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school'),
        ),
        migrations.CreateModel(
            name='AuthorizedPickup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authorized_pickups/')),
                ('secret_password', models.CharField(blank=True, help_text='Verbal verification password', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_pickups', to='students.student')),
            ],
            options={
                'verbose_name': 'Authorized Pickup Person',
                'verbose_name_plural': 'Authorized Pickup Persons',
                'db_table': 'authorized_pickups',
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('transfer_certificate', 'Transfer Certificate'), ('report_card', 'Report Card/Marksheet'), ('residence_proof', 'Residence Proof'), ('student_photo', 'Student Photograph'), ('parent_id_proof', 'Parent/Guardian ID Proof'), ('caste_certificate', 'Caste Certificate'), ('medical_certificate', 'Medical Fitness Certificate'), ('disability_certificate', 'Disability Certificate'), ('single_parent_proof', 'Single Parent Proof'), ('passport', 'Passport Copy'), ('visa', 'Visa Copy'), ('affidavit', 'Affidavit (No TC)'), ('local_guardian_photo', 'Local Guardian Photo'), ('authorized_pickup_photo', 'Authorized Pickup Photo'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Document',
                'verbose_name_plural': 'Student Documents',
                'db_table': 'student_documents',
                'ordering': ['document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentHealth',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('has_asthma', models.BooleanField(default=False)),
                ('asthma_action_plan', models.JSONField(blank=True, default=dict, help_text='Green/Yellow/Red zones')),
                ('has_diabetes', models.BooleanField(default=False)),
                ('diabetes_protocol', models.JSONField(blank=True, default=dict, help_text='Insulin, glucagon details')),
                ('has_epilepsy', models.BooleanField(default=False)),
                ('epilepsy_protocol', models.JSONField(blank=True, default=dict)),
                ('other_conditions', models.TextField(blank=True)),
                ('allergies_dietary', models.JSONField(blank=True, default=list, help_text='peanuts, gluten, dairy')),
                ('allergies_environmental', models.JSONField(blank=True, default=list, help_text='bee stings, pollen')),
                ('allergies_medicinal', models.JSONField(blank=True, default=list, help_text='penicillin, aspirin')),
                ('vaccine_bcg_date', models.DateField(blank=True, null=True)),
                ('vaccine_dpt_date', models.DateField(blank=True, null=True)),
                ('vaccine_polio_date', models.DateField(blank=True, null=True)),
                ('vaccine_mmr_date', models.DateField(blank=True, null=True)),
                ('vaccine_hepatitis_b_date', models.DateField(blank=True, null=True)),
                ('vaccine_varicella_date', models.DateField(blank=True, null=True)),
                ('wears_glasses', models.BooleanField(default=False)),
                ('uses_hearing_aid', models.BooleanField(default=False)),
                ('mobility_aid', models.CharField(blank=True, help_text='Crutches/Wheelchair/None', max_length=50)),
                ('doctor_name', models.CharField(blank=True, max_length=100)),
                ('doctor_phone', models.CharField(blank=True, max_length=20)),
                ('hospital_preference', models.CharField(blank=True, max_length=200)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Health Record',
                'verbose_name_plural': 'Student Health Records',
                'db_table': 'student_health',
            },
        ),
    ]
