# Generated by Django 6.0 on 2026-01-11 05:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric')], default='diesel', max_length=20),
        ),
        migrations.AddField(
            model_name='bus',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bus',
            name='purchase_date',
            field=models.DateField(blank=True, help_text='Date when bus was purchased (for age calculation)', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_distance_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total distance traveled in kilometers', max_digits=12),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_duration_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total time traveled in hours', max_digits=10),
        ),
        migrations.CreateModel(
            name='BusEarning',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('earning_type', models.CharField(choices=[('trip', 'Trip Fee'), ('monthly', 'Monthly Subscription'), ('special', 'Special Trip'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='transport.bus')),
                ('trip', models.ForeignKey(blank=True, help_text='Link to specific trip if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='transport.trip')),
            ],
            options={
                'verbose_name': 'Bus Earning',
                'verbose_name_plural': 'Bus Earnings',
                'db_table': 'bus_earnings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BusExpense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('fuel', 'Fuel'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('repair', 'Repair'), ('tax', 'Tax/Registration'), ('cleaning', 'Cleaning'), ('salary', 'Staff Salary'), ('parking', 'Parking/Toll'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField()),
                ('receipt_url', models.CharField(blank=True, help_text='URL to uploaded receipt image', max_length=500)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='transport.bus')),
            ],
            options={
                'verbose_name': 'Bus Expense',
                'verbose_name_plural': 'Bus Expenses',
                'db_table': 'bus_expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BusFuelEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odometer_reading', models.DecimalField(blank=True, decimal_places=2, help_text='Odometer reading at time of fill', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_entries', to='transport.bus')),
            ],
            options={
                'verbose_name': 'Bus Fuel Entry',
                'verbose_name_plural': 'Bus Fuel Entries',
                'db_table': 'bus_fuel_entries',
                'ordering': ['-date'],
            },
        ),
    ]
