# Generated by Django 6.0 on 2026-01-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_bus_fuel_type_bus_images_bus_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='distance_traveled',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance traveled in this trip (km)', max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Duration of trip in minutes'),
        ),
    ]
