# Generated by Django 6.0 on 2026-01-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_trip_distance_traveled_trip_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fitness_expiry_date',
            field=models.DateField(blank=True, help_text='Date when fitness certificate expires', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Date when insurance policy expires', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_maintenance_date',
            field=models.DateField(blank=True, help_text='Date of last scheduled maintenance', null=True),
        ),
    ]
