# Generated by Django 6.0 on 2026-01-25 06:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_pickup_address_and_more'),
        ('transport', '0004_bus_fitness_expiry_date_bus_insurance_expiry_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTransportHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_history', to='transport.bus')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conductor_student_history', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_student_history', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_history', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Transport History',
                'verbose_name_plural': 'Student Transport History',
                'db_table': 'student_transport_history',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['student', '-start_date'], name='student_tra_student_609518_idx'), models.Index(fields=['driver', 'academic_year'], name='student_tra_driver__f5605f_idx')],
            },
        ),
    ]
